/*
 * MATLAB Compiler: 3.0
 * Date: Sat Sep 04 22:31:38 2004
 * Arguments: "-B" "macro_default" "-O" "all" "-O" "fold_scalar_mxarrays:on"
 * "-O" "fold_non_scalar_mxarrays:on" "-O" "optimize_integer_for_loops:on" "-O"
 * "array_indexing:on" "-O" "optimize_conditionals:on" "-t" "-W" "lib:Pkg" "-T"
 * "link:exe" "-h" "mrank" "mrankp.c" "libmmfile.mlib" 
 */

#ifndef MLF_V2
#define MLF_V2 1
#endif

#include "libmatlb.h"
#include "Pkg.h"
#include "mrank.h"
#include "libmmfile.h"

extern _mex_information _lib_info;

static mexFunctionTableEntry function_table[1]
  = { { "mrank", mlxMrank, 1, 1, &_local_function_table_mrank } };

static _mexInitTermTableEntry init_term_table[2]
  = { { libmmfileInitialize, libmmfileTerminate },
      { InitializeModule_mrank, TerminateModule_mrank } };

static int _reference_count = 0;

_mex_information _lib_info
  = { 1, 1, function_table, 0, NULL, 0, NULL, 2, init_term_table };

/*
 * The function "PkgInitialize" is a Compiler-generated initialization wrapper.
 * It is used to initialize the state of Compiler-generated functions so that
 * those functions can be called from code not generated by the Compiler. The
 * function(s) initialized can be found in the function_table variable,
 * appearing above.
 */
void PkgInitialize(void) {
    mclLibInit("Pkg", &_reference_count, &_lib_info);
}

/*
 * The function "PkgTerminate" is a Compiler-generated termination wrapper. It
 * is used to clean up the state that was set up by the initialization wrapper
 * function, also found in this file. Call this function after having called
 * the initialization wrapper function and after having finished making all
 * calls to the Compiler-generated function(s) found in the function_table
 * variable, appearing above.
 */
void PkgTerminate(void) {
    mclLibTerm("Pkg", &_reference_count, &_lib_info);
}
